apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/alexandergg-0520/portfolio
    digest: sha256:bd46fa5cf62ff80e0fdd9ffba2da0a7757d25c5c782a254ef74ed2dd59e791ad
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: portfolio
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: PORTFOLIO_ENVIRONMENT
          value: production
