apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/alexandergg-0520/portfolio
    digest: sha256:4fd64adab2f1fddb6002a33461d5084bf064a72f21b61e93ea64bf78ceb3ef07
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: portfolio
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: PORTFOLIO_ENVIRONMENT
          value: production
