apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/alexandergg-0520/portfolio
    digest: sha256:6520c0e02357d7e043cb2564fae263b62130c2fbaee5e82e030427ce30cd22d9
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: portfolio
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: PORTFOLIO_ENVIRONMENT
          value: production
